/* Generated By:JavaCC: Do not edit this line. BasicParserConstants.java */
package de.haupz.basicode.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int COLON = 3;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int ABS = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int ASC = 11;
  /** RegularExpression Id. */
  int ATN = 12;
  /** RegularExpression Id. */
  int CHRS = 13;
  /** RegularExpression Id. */
  int COS = 14;
  /** RegularExpression Id. */
  int DATA = 15;
  /** RegularExpression Id. */
  int DIM = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int GOSUB = 19;
  /** RegularExpression Id. */
  int GOTO = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int INPUT = 23;
  /** RegularExpression Id. */
  int LEFTS = 24;
  /** RegularExpression Id. */
  int LEN = 25;
  /** RegularExpression Id. */
  int LET = 26;
  /** RegularExpression Id. */
  int LOG = 27;
  /** RegularExpression Id. */
  int MIDS = 28;
  /** RegularExpression Id. */
  int NEXT = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int ON = 31;
  /** RegularExpression Id. */
  int OR = 32;
  /** RegularExpression Id. */
  int PRINT = 33;
  /** RegularExpression Id. */
  int READ = 34;
  /** RegularExpression Id. */
  int REM = 35;
  /** RegularExpression Id. */
  int RESTORE = 36;
  /** RegularExpression Id. */
  int RETURN = 37;
  /** RegularExpression Id. */
  int RIGHTS = 38;
  /** RegularExpression Id. */
  int RUN = 39;
  /** RegularExpression Id. */
  int SGN = 40;
  /** RegularExpression Id. */
  int SIN = 41;
  /** RegularExpression Id. */
  int SQR = 42;
  /** RegularExpression Id. */
  int STEP = 43;
  /** RegularExpression Id. */
  int STOP = 44;
  /** RegularExpression Id. */
  int TAB = 45;
  /** RegularExpression Id. */
  int TAN = 46;
  /** RegularExpression Id. */
  int THEN = 47;
  /** RegularExpression Id. */
  int TO = 48;
  /** RegularExpression Id. */
  int VAL = 49;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\":\"",
    "<NUMBER>",
    "<INTEGER>",
    "<FLOAT>",
    "<DIGIT>",
    "<STRING>",
    "\"ABS\"",
    "\"AND\"",
    "\"ASC\"",
    "\"ATN\"",
    "\"CHR$\"",
    "\"COS\"",
    "\"DATA\"",
    "\"DIM\"",
    "\"END\"",
    "\"FOR\"",
    "\"GOSUB\"",
    "\"GOTO\"",
    "\"INT\"",
    "\"IF\"",
    "\"INPUT\"",
    "\"LEFT$\"",
    "\"LEN\"",
    "\"LET\"",
    "\"LOG\"",
    "\"MID$\"",
    "\"NEXT\"",
    "\"NOT\"",
    "\"ON\"",
    "\"OR\"",
    "\"PRINT\"",
    "\"READ\"",
    "<REM>",
    "\"RESTORE\"",
    "\"RETURN\"",
    "\"RIGHT$\"",
    "\"RUN\"",
    "\"SGN\"",
    "\"SIN\"",
    "\"SQR\"",
    "\"STEP\"",
    "\"STOP\"",
    "\"TAB\"",
    "\"TAN\"",
    "\"THEN\"",
    "\"TO\"",
    "\"VAL\"",
    "<IDENTIFIER>",
    "\",\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
  };

}
