package de.haupz.basicode.io;

/**
 * A tuple representing a single key press, with the key code and character stored separately.
 *
 * @param code the key code of the key pressed.
 * @param character the character generated by the key pressed.
 */
public record KeyPress(int code, char character) {}
